import Header from "../component/header";

export const metadata = {
    title: "Blockchain",
    // description: "Generated by create next app",
  };

export default function Home() {
  return (
    <>

    {/* <div id="preloader">
        <div className="spinner">
            <div className="rect1"></div>
            <div className="rect2"></div>
            <div className="rect3"></div>
            <div className="rect4"></div>
            <div className="rect5"></div>
        </div>
    </div> */}
<body class="home-purple-gradient">

    <button className="scroll-top scroll-to-target" data-target="html">
        <i className="fas fa-angle-up"></i>
    </button>
  
    {/* <header id="header" className="header-layout1">
        <div id="sticky-header" className="menu-area transparent-header">
            <div className="container custom-container">
                <div className="row">
                    <div className="col-12">
                        <div className="menu-wrap">
                            <nav className="menu-nav">
                                <div className="logo">
                                    <a href="/"><img src="/assets/img/logo/logo.png" style={{height: "200px"}} alt="Logo"/></a>
                                </div>
                                <div className="navbar-wrap main-menu d-none d-lg-flex">
                                    <ul className="navigation">
                                        <li className="active menu-item-has-children"><a className="section-link" href="/">Home</a>
                                            <ul className="sub-menu">
                                                <li><a href="/">ICO Investment</a></li>
                                                <li className="active"><a href="/blockchain">Blockchain</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#blockchain" className="section-link">Why Blockchain</a></li>
                                        <li><a href="#feature" className="section-link">Feature</a></li>
                                        <li className="menu-item-has-children"><a href="#">blog</a>
                                            <ul className="sub-menu">
                                                <li><a href="/blog">Our Blog</a></li>
                                                <li><a href="/blogDetails">Blog Details</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="/contact">Contact</a></li>
                                    </ul>
                                </div>
                                <div className="header-action">
                                    <ul className="list-wrap">
                                        <li className="header-login"><Link className="btn2" href="/rollup">LOGIN</Link></li>
                                    </ul>
                                </div>
                                <div className="mobile-nav-toggler"><i className="fas fa-bars"></i></div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="mobile-menu">
            <nav className="menu-box">
                <div className="close-btn"><i className="fas fa-times"></i></div>
                <div className="nav-logo">
                    <a href="index.html"><img src="/assets/img/logo/logo.png" style={{height: "35px"}} alt="Logo"/></a>
                </div>
                <div className="menu-outer">
                </div>
                <div className="social-links">
                    <ul className="clearfix list-wrap">
                        <li><a href="#"><i className="fab fa-facebook-f"></i></a></li>
                        <li>
                            <a href="#">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                                    <path
                                        d="M10.0596 7.34522L15.8879 0.570312H14.5068L9.44607 6.45287L5.40411 0.570312H0.742188L6.85442 9.46578L0.742188 16.5703H2.12338L7.4676 10.3581L11.7362 16.5703H16.3981L10.0593 7.34522H10.0596ZM8.16787 9.54415L7.54857 8.65836L2.62104 1.61005H4.74248L8.71905 7.29827L9.33834 8.18405L14.5074 15.5779H12.386L8.16787 9.54449V9.54415Z"
                                        fill="currentColor"></path>
                                </svg>
                            </a>
                        </li>
                        <li><a href="#"><i className="fab fa-instagram"></i></a></li>
                        <li><a href="#"><i className="fab fa-linkedin-in"></i></a></li>
                        <li><a href="#"><i className="fab fa-youtube"></i></a></li>
                    </ul>
                </div>
            </nav>
        </div>
        <div className="menu-backdrop"></div>
    </header> */}
    <Header/>

    <div className="hero-wrapper hero-2">
        <div className="hero-bg-gradient1"></div>
        <div className="hero-bg-gradient2"></div>
        <div className="hero-gradient-ball alltuchtopdown"></div>
        <div className="ripple-shape">
            <span className="ripple-1"></span>
            <span className="ripple-2"></span>
            <span className="ripple-3"></span>
            <span className="ripple-4"></span>
            <span className="ripple-5"></span>
        </div>
        <div className="container">
            <div className="hero-style2">
                <div className="row">
                    <div className="col-lg-12">
                        <h6 className="hero-subtitle">GET NEW SOLUTION</h6>
                        <h1 className="hero-title">Blockcha<span>i<img className="bitcoin" src="assets/img/update/hero/bitcoin.svg" alt="img"/></span>n</h1>
                        <div className="btn-wrap">
                            <h3 className="hero-title2">Technology for business</h3>
                            <div className="hero-content">
                                <p className="hero-text">We’ve worked with over 400 companies to build blockchain solutions for their business, and we are still growing.</p>
                                <a href="contact.html" className="btn btn3" >
                                    Get Started Today
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
  
    <div className="brand-area3">
        <div className="container">
            <div className="row g-0">
                <div className="col-lg-12">
                    <div className="brand-title2 text-center">
                        <h6 className="title">Backed by leading Blockchain investors and founders</h6>
                    </div>
                </div>
            </div>
            <div className="brand-item-wrap3">
                <div className="row g-0 brand-active2">
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-1.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-2.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-3.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-4.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-5.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-1.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-2.svg" alt="img"/>
                        </div>
                    </div>
                    <div className="col-12">
                        <div className="brand-item">
                            <img src="/assets/img/update/client/client-2-3.svg" alt="img"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div className="feature-area-2 pt-110 pb-140 position-relative overflow-hidden" style={{backgroundImage: "url(assets/img/update/bg/feature-area-bg.png)" , backgroundSize: "cover", backgroundPosition: "center"}} id="blockchain">
        <div className="feature-area-shape">
            <img className="feature-shape2-1 alltuchtopdown" src="assets/img/update/feature/feature-shape-2-1.png" alt="img"/>
            <img className="feature-shape2-2 alltuchtopdown" src="assets/img/update/feature/feature-shape-2-2.png" alt="img"/>
            <img className="feature-shape2-3 leftToRight" src="assets/img/update/feature/feature-shape-2-3.png" alt="img"/>
        </div>
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-xl-5 col-lg-8">
                    <div className="section-title text-center mb-50">
                        <span className="sub-title">ABOUT BLOCKCHAIN</span>
                        <h2 className="title style2">Why blockchain?</h2>
                        <p className="sec-text">We’ve worked with over 400 companies to build blockchain solutions for their business, and we are still growing.
                        </p>
                    </div>
                </div>
            </div>
            <div className="feature-grid-wrap">
                <div className="feature-card-grid">
                    <div className="feature-card-details">
                        <h3 className="feature-card-title">Flexibility</h3>
                        <p className="feature-card-text">We’ve worked with over 400 companies to build blockchain solutions for their business.</p>
                        <div className="checklist">
                            <ul>
                                <li><i className="fas fa-circle"></i> Blockchain solutions for their business.</li>
                                <li><i className="fas fa-circle"></i> Blockchain solutions for their business.</li>
                                <li><i className="fas fa-circle"></i> Blockchain solutions for their business.</li>
                            </ul>
                        </div>
                    </div>
                    <div className="feature-card-img">
                        <img className="alltuchtopdown" src="assets/img/update/feature/feature-card-thumb-1.png" alt="img"/>
                    </div>
                </div>
                <div className="feature-card-grid">
                    <div className="feature-card-details">
                        <h3 className="feature-card-title">Transference</h3>
                        <p className="feature-card-text">We’ve worked with over 400 companies to build blockchain solutions for their business.</p>
                        <p className="feature-card-text">We’ve worked with over 400 companies to build</p>
                    </div>
                    <div className="feature-card-img">
                        <img src="/assets/img/update/feature/feature-card-thumb-2.png" alt="img"/>
                    </div>
                </div>
                <div className="feature-card-grid">
                    <div className="feature-card-details">
                        <h3 className="feature-card-title">Secure & Safe</h3>
                        <p className="feature-card-text">We’ve worked with over 400 companies to build blockchain solutions for their business.</p>
                        <p className="feature-card-text">We’ve worked with over 400 companies to build</p>
                    </div>
                    <div className="feature-card-img">
                        <img src="/assets/img/update/feature/feature-card-thumb-3.png" alt="img"/>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div className="pt-140 pb-140 overflow-hidden position-relative z-index-common" id="feature">
        <div className="bg-gradient-5"></div>
        <div className="feature-shape-3-1 alltuchtopdown"></div>
        <div className="feature-shape-3-2 alltuchtopdown"></div>
        <div className="container">
            <div className="row">
                <div className="col-xl-6 text-center">
                    <div className="feature-thumb-wrap">
                        <img className="feature-thumb-3-1 alltuchtopdown" src="assets/img/update/normal/intro_1-1.png" alt="img"/>
                        <img className="feature-thumb-3-2" src="assets/img/update/feature/feature-thumb-3-1.png" alt="img"/>
                        <div className="feature-thumb-circle spin"></div>
                    </div>
                </div>
                <div className="col-xl-5">
                    <div className="section-title mb-75">
                        <span className="sub-title text-white">FEATURES</span>
                        <h2 className="title style2">Blockchain spreads trust everywhere</h2>
                        <p className="mt-25">Our team has created blockchain solutions for over 400 companies, and we are still growing. From less paperwork and fewer disputes, to happier customers and entirely new business methods, <a className="text-decoration-underline text-white" href="#">a shared record of truth is invaluable.</a>
                        </p>
                    </div>
                    <div className="counter-grid-wrap">
                        <div className="counter-wrap">
                            <div className="counter-card">
                                <h3 className="counter-card_number">
                                    63M
                                </h3>
                                <p className="counter-card_text">Blockchain users</p>
                            </div>
                        </div>
                        <div className="counter-wrap">
                            <div className="counter-card">
                                <h3 className="counter-card_number">
                                    24%
                                </h3>
                                <p className="counter-card_text">Companies use blockchain</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div className="pt-140 pb-140 overflow-hidden position-relative z-index-common">
        <div className="feature-shape-4-1  spin"></div>
        <div className="feature-shape-4-2 alltuchtopdown"></div>
        <div className="feature-shape-4-3 alltuchtopdown"></div>
        <div className="feature-shape-4-4"></div>
        <div className="container">
            <div className="row justify-content-between align-items-center">
                <div className="col-xl-5">
                    <div className="section-title mb-50">
                        <span className="sub-title">POSSIBILITIES</span>
                        <h2 className="title style2">What does it mean for your business?</h2>
                
                        <p className="mt-25">We’ve worked with over 400 companies to build blockchain solutions for their business, and we are still growing.
                        </p>
                    </div>
                </div>
                <div className="col-xl-6">
                    <ul className="feature-category-list mb-xl-0 mb-60">
                        <li>
                            <a href="blog-details.html">Smart contracts</a>
                        </li>
                        <li>
                            <a href="blog-details.html">Paying employees</a>
                        </li>
                        <li>
                            <a href="blog-details.html">Cloud storage</a>
                        </li>
                        <li>
                            <a href="blog-details.html">Electronic voting</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div className="feature-wrap-4">
                <div className="row align-items-center">
                    <div className="col-lg-6">
                        <div className="feature-wrap4-thumb text-center alltuchtopdown">
                            <img src="/assets/img/update/normal/why_1-1.png" alt="img"/>
                        </div>
                    </div>
                    <div className="col-lg-6">
                        <div className="section-title mb-0">
                            <span className="sub-title text-title">FEATURES</span>
                            <h2 className="title style2 text-title">What does it mean for your business?</h2>
                            <p className="text-title mt-20 mb-55">Our team has created blockchain solutions for over 400 companies, and we are still growing. From less paperwork and fewer disputes, to happier customers and entirely new business methods, <a className="text-title text-decoration-underline" href="#">a shared record of truth is invaluable.</a></p>
                            <a href="contact.html" className="btn btn btn3">
                                Get started
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 
    <div className="pb-140 overflow-hidden">
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-lg-8">
                    <div className="section-title text-center mb-50">
                        <span className="sub-title">TESTIMONIAL</span>
                        <h2 className="title style2">Over 400 companies have already tried blockchain</h2>
                    </div>
                </div>
            </div>

            <div className="testimonial-wrap-3">
                <div className="testimonial-wrap-circle1 alltuchtopdown"></div>
                <div className="testimonial-wrap-circle2 leftToRight"></div>
                <div className="testimonial-wrap-circle3 leftToRight"></div>
                <div className="testimonial-wrap-bg alltuchtopdown">
                    <img src="/assets/img/update/bg/testimonial-4-bg.png" alt="img"/>
                </div>
                <div className="slider-area testimonial-slider-wrap">
                    <div className="row testimonial-slider1">
                        <div className="col-lg-6 slider-item">
                            <div className="testi-box ">
                                <div className="testi-box-profile">
                                    <div className="testi-box-profile-thumb">
                                        <img src="/assets/img/update/testimonial/testi_thumb1_1.png" alt="img"/>
                                    </div>
                                    <div className="testi-box-profile-details">
                                        <h4 className="testi-box_name">Romero Eli</h4>
                                        <span className="testi-box_desig">Developer</span>
                                    </div>
                                    <div className="testi-box-profile-ratting">
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                    </div>
                                </div>
                                <p className="testi-box_text">I've tested numerous technologies, but this one is leaps and bounds ahead of the competition. It's phenomenal.</p>
                            </div>
                        </div>
                        <div className="col-lg-6 slider-item">
                            <div className="testi-box ">
                                <div className="testi-box-profile">
                                    <div className="testi-box-profile-thumb">
                                        <img src="/assets/img/update/testimonial/testi_thumb1_2.png" alt="img"/>
                                    </div>
                                    <div className="testi-box-profile-details">
                                        <h4 className="testi-box_name">Gomez Goles</h4>
                                        <span className="testi-box_desig">Product Designers</span>
                                    </div>
                                    <div className="testi-box-profile-ratting">
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                    </div>
                                </div>
                                <p className="testi-box_text">I can't express how impressed I am with this technology. It outshines anything I've ever used before & up to the mark.</p>
                            </div>
                        </div>
                        <div className="col-lg-6 slider-item">
                            <div className="testi-box ">
                                <div className="testi-box-profile">
                                    <div className="testi-box-profile-thumb">
                                        <img src="/assets/img/update/testimonial/testi_thumb1_1.png" alt="img"/>
                                    </div>
                                    <div className="testi-box-profile-details">
                                        <h4 className="testi-box_name">Romero Eli</h4>
                                        <span className="testi-box_desig">Developer</span>
                                    </div>
                                    <div className="testi-box-profile-ratting">
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                    </div>
                                </div>
                                <p className="testi-box_text">I've tested numerous technologies, but this one is leaps and bounds ahead of the competition. It's phenomenal.</p>
                            </div>
                        </div>
                        <div className="col-lg-6 slider-item">
                            <div className="testi-box ">
                                <div className="testi-box-profile">
                                    <div className="testi-box-profile-thumb">
                                        <img src="/assets/img/update/testimonial/testi_thumb1_2.png" alt="img"/>
                                    </div>
                                    <div className="testi-box-profile-details">
                                        <h4 className="testi-box_name">Gomez Goles</h4>
                                        <span className="testi-box_desig">Product Designers</span>
                                    </div>
                                    <div className="testi-box-profile-ratting">
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                        <i className="fas fa-star"></i>
                                    </div>
                                </div>
                                <p className="testi-box_text">I can't express how impressed I am with this technology. It outshines anything I've ever used before & up to the mark.</p>
                            </div>
                        </div>
                    </div>
                    <button data-slider-prev=".testimonial-slider1" className="slider-arrow prev-btn"><i className="fas fa-arrow-left"></i></button>
                    <button data-slider-next=".testimonial-slider1" className="slider-arrow next-btn"><i className="fas fa-arrow-right"></i></button>
                </div>

            </div>
        </div>
    </div>


    <div className="pt-140 pb-140 position-relative z-index-common">
        <div className="bg-gradient-5"></div>
        <div className="cta-2-shape1 alltuchtopdown"><img src="/assets/img/update/bg/cta-2-shape1.png" alt="img"/></div>
        <div className="cta-2-shape2 alltuchtopdown"></div>
        <div className="cta-2-shape3 leftToRight"></div>
        <div className="container">
            <div className="cta-wrap2 pt-140 pb-140" style={{backgroundImage: "url(assets/img/update/bg/cta-2-bg.png)", backgroundSize: "cover"}}>
                <div className="row gy-40 align-items-center">
                    <div className="col-xl-6 col-lg-8">
                        <div className="section-title mb-50">
                            <span className="sub-title text-white">TECHNOLOGY</span>
                            <h2 className="title style2">How does blockchain work for business?</h2>
                            <p className="sec-text text-white">We’ve worked with over 400 companies to build blockchain solutions for their business, and we are still growing.</p>
                        </div>
                        <a href="contact.html" className="btn btn3">
                            Get started
                        </a>
                    </div>
                    <div className="col-xl-6 col-lg-4">
                        <div className="text-lg-center">
                            <a href="https://www.youtube.com/watch?v=vvNwlRLjLkU" className="play-btn popup-video">
                                <i>
                                    <svg width="22" height="23" viewBox="0 0 22 23" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M1.66602 11.6553V7.50193C1.66602 2.34526 5.31768 0.233597 9.78602 2.81193L13.391 4.8886L16.996 6.96526C21.4643 9.5436 21.4643 13.7669 16.996 16.3453L13.391 18.4219L9.78602 20.4986C5.31768 23.0769 1.66602 20.9653 1.66602 15.8086V11.6553Z" stroke="white" strokeWidth="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/>
                                    </svg>
                                </i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div className="pt-140 pb-140 overflow-hidden position-relative z-index-common">
        <div className="faq-2-shape-1"></div>
        <div className="container">
            <div className="row justify-content-center">
                <div className="col-xl-6 text-center">
                    <div className="section-title mb-50">
                        <span className="sub-title">FAQ</span>
                        <h2 className="title style2">Popular questions about blockchain</h2>
                        <p className="sec-text">We’ve worked with over 400 companies to build blockchain solutions for their business, and we are still growing.</p>
                    </div>
                </div>
            </div>
            <div className="row justify-content-center">
                <div className="col-lg-10">
                    <div className="accordion-area accordion" id="faqAccordion">

                        <div className="accordion-card style2">
                            <div className="accordion-header" id="collapse-item-1">
                                <button className="accordion-button " type="button" data-bs-toggle="collapse" data-bs-target="#collapse-1" aria-expanded="true" aria-controls="collapse-1">What is blockchain technology?</button>
                            </div>
                            <div id="collapse-1" className="accordion-collapse collapse show" aria-labelledby="collapse-item-1" data-bs-parent="#faqAccordion">
                                <div className="accordion-body">
                                    <p className="faq-text">It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.</p>
                                </div>
                            </div>
                        </div>


                        <div className="accordion-card style2">
                            <div className="accordion-header" id="collapse-item-2">
                                <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-2" aria-expanded="false" aria-controls="collapse-2">What is Bitcoin?
                                </button>
                            </div>
                            <div id="collapse-2" className="accordion-collapse collapse " aria-labelledby="collapse-item-2" data-bs-parent="#faqAccordion">
                                <div className="accordion-body">
                                    <p className="faq-text">It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.</p>
                                </div>
                            </div>
                        </div>


                        <div className="accordion-card style2">
                            <div className="accordion-header" id="collapse-item-3">
                                <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-3" aria-expanded="false" aria-controls="collapse-3">Who created Bitcoin?</button>
                            </div>
                            <div id="collapse-3" className="accordion-collapse collapse " aria-labelledby="collapse-item-3" data-bs-parent="#faqAccordion">
                                <div className="accordion-body">
                                    <p className="faq-text">It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.</p>
                                </div>
                            </div>
                        </div>

                        <div className="accordion-card style2">
                            <div className="accordion-header" id="collapse-item-4">
                                <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-4" aria-expanded="false" aria-controls="collapse-4">What is cryptocurrency?</button>
                            </div>
                            <div id="collapse-4" className="accordion-collapse collapse " aria-labelledby="collapse-item-4" data-bs-parent="#faqAccordion">
                                <div className="accordion-body">
                                    <p className="faq-text">It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.</p>
                                </div>
                            </div>
                        </div>

                        <div className="accordion-card style2">
                            <div className="accordion-header" id="collapse-item-5">
                                <button className="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-5" aria-expanded="false" aria-controls="collapse-5">How does cryptocurrency  work?</button>
                            </div>
                            <div id="collapse-5" className="accordion-collapse collapse " aria-labelledby="collapse-item-5" data-bs-parent="#faqAccordion">
                                <div className="accordion-body">
                                    <p className="faq-text">It's very simple! Register here. In your personal account, create a wallet where you can store your FOX tokens. Then just send any amount to the displayed address in your office.</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div className="pb-120 position-relative z-index-common">
        <div className="container">
            <div className="cta-wrap3">
                <div className="cta-wrap-details">
                    <div className="section-title mb-20">
                        <h2 className="title style2 text-title">Be part of the future</h2>
                        <p className="sec-text text-title">We’ve worked with over 400 companies to build blockchain solutions for their business.</p>
                    </div>
                    <a href="contact.html" className="btn btn3">
                        Get started
                    </a>
                </div>
                <div className="cta-3-thumb movingX">
                    <img src="/assets/img/update/normal/cta_3-1.png" alt="img"/>
                </div>
            </div>
        </div>
    </div>

  
    <footer className="footer-wrapper footer-layout2 pb-50">
        <div className="container">
            <div className="row justify-content-between">
                <div className="col-xl-auto col-lg-6 order-xl-1">
                    <div className="widget footer-widget">
                        <div className="widget-about">
                            <div className="footer-logo">
                                <a href="index.html"><img src="/assets/img/logo/logo.png" style={{height: "35px"}} alt="iko"/></a>
                            </div>
                            <p className="about-text">Iko is a cutting-edge blockchain technology company at the forefront of innovation in the decentralized ledger space. Established in 2024</p>
                            <div className="social-btn style2">
                                <a href="https://facebook.com/"><i className="fab fa-facebook-f"></i></a>
                                <a href="#">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                                        <path
                                            d="M10.0596 7.34522L15.8879 0.570312H14.5068L9.44607 6.45287L5.40411 0.570312H0.742188L6.85442 9.46578L0.742188 16.5703H2.12338L7.4676 10.3581L11.7362 16.5703H16.3981L10.0593 7.34522H10.0596ZM8.16787 9.54415L7.54857 8.65836L2.62104 1.61005H4.74248L8.71905 7.29827L9.33834 8.18405L14.5074 15.5779H12.386L8.16787 9.54449V9.54415Z"
                                            fill="currentColor"></path>
                                    </svg>
                                </a>
                                <a href="https://www.instagram.com/"><i className="fab fa-instagram"></i></a>
                                <a href="https://www.linkedin.com/"><i className="fab fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-xl-auto col-lg-6 order-xl-3">
                    <div className="footer-widget widget-newsletter">
                        <h3 className="fw-title">SIGN UP FOR EMAIL UPDATES</h3>
                        <p className="newsletter-text">Sign up with your email address to receive news and updates</p>
                        <form className="newsletter-form">
                            <div className="form-group">
                                <input className="form-control" type="email" placeholder="Your Email Address" required=""/>
                            </div>
                            <button type="submit" className="btn btn5">Subscribe</button>
                        </form>
                    </div>
                </div>
                <div className="col-xl-auto col-lg-6 order-xl-2">
                    <div className="footer-widget widget-contact">
                        <h3 className="fw-title">CONTACT US</h3>
                        <p className="contact-info-text">202 Helga Springs Rd, Crawford, TN 38554</p>
                        <div className="contact-info-link">Call Us: <a href="tel:8002758777">800.275.8777</a></div>
                        <div className="contact-info-link"><a href="mailto:iko@company.com">iko@company.com</a></div>
                        <p className="copyright-text">Copyright © 2024 <a href="#">IKO.</a> All rights reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="assets/js/vendor/jquery-3.6.0.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/jquery.countdown.min.js"></script>
    <script src="assets/js/jquery.appear.js"></script>
    <script src="assets/js/slick.min.js"></script>
    <script src="assets/js/ajax-form.js"></script>
    <script src="assets/js/jquery.easing.js"></script>
    <script src="assets/js/imagesloaded.pkgd.min.js"></script>
    <script src="assets/js/isotope.pkgd.min.js"></script>
    <script src="assets/js/jquery.magnific-popup.min.js"></script>
    <script src="assets/js/wow.min.js"></script>
    <script src="assets/js/main.js"></script>
</body>
    </>
  );
}
